### ISSUE TITLE
CSS for Event Overflow

### ISSUE THREAD

**Issue by dengel29** [yaycake/wx_orm_mp#54]
Because I had made some more critical changes that would've screwed up your next pull of the MP, I'll just add the snippet for the text-overflow here. I recommend it would just be easier to add these 3 lines of CSS in your next merge:

(in components/card_event/card_event.wxss)
```css
.textBottom {
  margin-top: .5rem;
  white-space: nowrap;
  overflow-y: hidden;
  text-overflow: ellipsis;
}
```
The text-overflow ellipsis didn't seem to work, so is optional. Would be nice to find if it can work for MP though.
